---
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install molecule docker-py molecule-docker ansible
script:
  - molecule --version
  - ansible --version
  - molecule test
