- name: Add APT key
  apt_key:
    id: "EA312927"
    keyserver: keyserver.ubuntu.com
  tags: install

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: apt update
  apt:
    update_cache=yes
    force_apt_get=yes
  tags: install

- name: Install mongodb package
  apt:
    name: mongodb-org
    allow_unauthenticated: yes
    force_apt_get: yes
    state: present
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
