---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
    #lint: |
      #yamllint
platforms:
  - name: instance
    box: bento/ubuntu-16.04
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: testinfra

